import 'package:polkadex/features/landing/models/home_models.dart';
import 'package:polkadex/utils/enums.dart';
import 'package:polkadex/utils/extensions.dart';

/// The dummy data
final basicCoinDummyList = <BasicCoinListModel>[
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_6.png'.asAssetImg(),
    amount: "\$476,876",
    name: 'Polkadex',
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 800108,
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_2.png'.asAssetImg(),
    amount: "\$476,876",
    name: 'Bitcoin',
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 700122,
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_3.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    name: 'Tether',
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 500912,
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_4.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 788752,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_5.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 898906,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_6.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 678238,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_7.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 129093,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_8.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 789239,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_9.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 908731,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_10.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.buy,
    volume: 678290,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_11.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 800308,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_12.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 890122,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_6.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 530912,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_2.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 878752,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_3.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 688906,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_4.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 548238,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_5.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 219093,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_6.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 879239,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_7.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 898731,
    name: 'Polkadot',
  ),
  BasicCoinListModel(
    imgAsset: 'trade_open/trade_open_8.png'.asAssetImg(),
    amount: "\$476,876",
    code: "BTC",
    pair: "USDT",
    token: "BTC",
    percentage: 13.09,
    buySell: EnumBuySell.sell,
    volume: 778290,
    name: 'Polkadot',
  ),
];
