name: Build Polkadex App

on:
  push:
    branches: [main]
  pull_request:
    branches: [develop]

env:
  PROPERTIES_FILE_PATH: "android/key.properties"
  ENV_FILE_PATH: ".env"
  STORE_FILE_PATH: "../app/upload-keystore.jks"

jobs:
  buildapk:
    name: Build Polkadex App for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Check for formatting issues in the code
        run: flutter format . --set-exit-if-changed
      - name: Create .env file using repo secrets
        run: |
          echo BLOCKCHAIN_URL=\${{ secrets.BLOCKCHAIN_URL }} > ${{env.ENV_FILE_PATH}}
          echo API_KEY=\${{ secrets.API_KEY }} >> ${{env.ENV_FILE_PATH}}
          echo GRAPHQL_ENDPOINT=\${{ secrets.GRAPHQL_ENDPOINT }} >> ${{env.ENV_FILE_PATH}}
          echo GRAPHQL_ENDPOINT_WEBSOCKET=\${{ secrets.GRAPHQL_ENDPOINT_WEBSOCKET }} >> ${{env.ENV_FILE_PATH}}
          echo API_NAME=\${{ secrets.API_NAME }} >> ${{env.ENV_FILE_PATH}}
          echo REGION=\${{ secrets.REGION }} > ${{env.ENV_FILE_PATH}}
      - name: Check for errors in the code
        run: flutter analyze .
      - name: Run tests
        run: flutter test
      - name: Create properties file using secrets
        run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_FILE_PATH}}
          echo storePassword=\${{ secrets.KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_FILE_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_FILE_PATH}}
          echo storeFile=../app/key.jks >> ${{env.PROPERTIES_FILE_PATH}}
      - name: Create .jks signing file
        run: echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > android/app/key.jks
      - name: Build Android App
        run: flutter build apk
      - name: Upload .apk to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-builds-apk
          path: |
            build/app/outputs/apk/release/*.apk
  buildios:
    name: Build Polkadex App for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Check for formatting issues in the code
        run: flutter format . --set-exit-if-changed
      - name: Create .env file using repo secrets
        run: |
          echo BLOCKCHAIN_URL=\${{ secrets.BLOCKCHAIN_URL }} > ${{env.ENV_FILE_PATH}}
          echo API_KEY=\${{ secrets.API_KEY }} >> ${{env.ENV_FILE_PATH}}
          echo GRAPHQL_ENDPOINT=\${{ secrets.GRAPHQL_ENDPOINT }} >> ${{env.ENV_FILE_PATH}}
          echo GRAPHQL_ENDPOINT_WEBSOCKET=\${{ secrets.GRAPHQL_ENDPOINT_WEBSOCKET }} >> ${{env.ENV_FILE_PATH}}
          echo API_NAME=\${{ secrets.API_NAME }} >> ${{env.ENV_FILE_PATH}}
          echo REGION=\${{ secrets.REGION }} > ${{env.ENV_FILE_PATH}}
      - name: Create properties file using secrets
        run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_FILE_PATH}}
          echo storePassword=\${{ secrets.KEYSTORE_PASSWORD }} >> ${{env.PROPERTIES_FILE_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_FILE_PATH}}
          echo storeFile=../app/key.jks >> ${{env.PROPERTIES_FILE_PATH}}
      - name: Create .jks signing file
        run: echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > android/app/key.jks
      - name: Build iOS App
        run: flutter build ios --no-codesign
      - name: Upload .ipa to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-builds-ios
          path: |
            build/ios/iphoneos/*.app
